# If you want to try the "Relaxed Style" uncomment
# the following two lines and remove everything else.
#  inherit_from:
#    - https://relaxed.ruby.style/rubocop.yml

# If you wna to try the "Shopify Style" uncomment
# the following two lines and remove everythig else.
# inherit_from:
#   - https://shopify.github.io/ruby-style-guide/rubocop.yml


# The following is the "Full Stack RRC Style".
# Please let Kyle know if there are other folders or cops you
# think should be disabled or tweaked in this file.

AllCops:
  Exclude:
    - db/**/*
    - Gemfile

Style/Encoding:
  Enabled: false

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Style/InlineComment:
  Description: 'Avoid inline comments.'
  Enabled: false

Layout/LineLength:
  Description: 'Limit lines to 90 characters. (Default is 80)'
  Max: 90

Style/FrozenStringLiteralComment:
  Description: To help transition from Ruby 2.3.0 to Ruby 3.0.
  Enabled: false

Style/WordArray:
  Description: 'Use %w or %W for arrays of words.'
  Enabled: false

# Defaults all strings to double quotes. Less performant, but
# nicer for consistency, and for adding interpolation later.
Style/StringLiterals:
  EnforcedStyle: double_quotes

# Prettier hashes.
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

# No auto-correct for unused block arguments,
# but will still warn.
Lint/UnusedBlockArgument:
  AutoCorrect: false

# No auto-correct for unused method arguments,
# but will still warn.
Lint/UnusedMethodArgument:
  AutoCorrect: false